source 'https://rubygems.org'

gem 'jekyll'
gem 'terminal-notifier'
gem 'terminal-notifier-guard'
gem 'jekyll-assets'
gem 'uglifier'
gem 'sass'
gem 'closure-compiler'
gem 'haml'
gem 'rack-jekyll', git: 'git://github.com/adaoraul/rack-jekyll.git'
